-- CreateEnum
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'SyncJobType') THEN
    CREATE TYPE "SyncJobType" AS ENUM ('ANILIST_SYNC', 'EPISODE_METADATA');
  END IF;
END $$;

-- AlterTable
ALTER TABLE "SyncJob" ADD COLUMN IF NOT EXISTS "type" "SyncJobType" NOT NULL DEFAULT 'ANILIST_SYNC';
ALTER TABLE "SyncJob" ADD COLUMN IF NOT EXISTS "details" JSONB;
