server {
    listen 80;
    server_name _;

    root /downloads;
    autoindex off;

    add_header Accept-Ranges bytes;

    location / {
        if ($request_method !~ ^(GET|HEAD)$) {
            return 405;
        }
        add_header Cache-Control "no-cache";
        add_header Accept-Ranges bytes;
        try_files $uri =404;
    }

    location ~ /\. {
        deny all;
    }
}
